### PR TITLE
Abstractfile

### PR DESCRIPTION
**Pull request by allartk**
A follow up, so it includes minimal phpunit testing in previous pull request.

Changes:
* Allow usage of other abstract filesystems (like flysystem)
* Run php-cs-fixer...

Api break: yes.

### CODE REVIEW

**Comment by gasparesganga** [comment]
Ok, here it goes the second part after my previous answer here: https://github.com/gasparesganga/php-shapefile/pull/10#issuecomment-328900968.

As I had already wrote in reply to other pull requests, my open source projects follow a strict development and deployment path that involves some private repositories too. Long story short, I won't accept any pull request that isn't *strictly necessary*  before auditing and testing it myself.
Of course I am keen to give credits to eventual contributors for their ideas and feedback, but since I do this in my spare time and I actually use my libraries for other projects, I prefer to keep 100% control over them.

About the changes in the main `Shapefile.php` file, I like the microoptimization of the pre-incrementing `++$i`, but I don't get why you dropped all the separating spaces, they help reading the code...

Anyways, seriously, I think there's no need to break change the library itself to support your abstract filesystem, why don't you just **extend** the `Shapefile` class and use a custom constructor?
This way you can keep using the latest release of my library *wrapping* your own code around it.

**Comment by allartk** [comment]
My editor does fix psr code standard violations.
Extending does not work because private methods called from the constructor. I see you think very different and do not aim to follow standards, public testing scripts to make collabaration possible. This is unfortunate, but we will go a different path.

**Comment by gasparesganga** [comment]
About the PSR standards, I don't use/trust any editor/linter, but I like to read the specs, so it turns out there's something I had missed and something that your editor missed too:
* Are multiple spaces after a variable name prohibited by PSR code standards? I can't really find anything like that in PSR-2. Spaces are regulated around namespaces, methods, method arguments, keywords and control structures, or am I missing something?
* About the `if` control structures, I had missed the final sentence of point [5 Control Structures](http://www.php-fig.org/psr/psr-2/#control-structures) in PSR-2, you are right about enclosing all the bodies in curly braces and avoid one-line statements, my bad.
* The final *comma* added after the last element of any array is not mandated in any standard, that's just a personal preference. I don't like it, but hey, everybody has his preferences ;)

About the *standard testing* and collaborative development, well, you are right, I am not aiming at it. But that's not necessarly something bad. I have been developing a few libraries and pieces of code as part of a bigger framework for my company and I was able to release part of them as open source projects. They can be considered as *public forks* of a private project. The fallback is that I have to be pretty strict with the development and I don't have much free time to audit other code.

Now, let's go back to what really matters, the code. You are right, there are some private methods calls in the constructor. I can release a new version and declare `private` methods as `protected` so you will be able to extend the Class as much as you like, would it be ok?
I appreciate all the feedback and I will be more than happy to modify the library in order to give you and other people the chance to use it in your projects.

---
**EDIT:**
Thinking about it, I could do even better: no need to declare many `protected` methods, I can just encapsulate the *init* logic into a single `protected` method to be called from the constructor. This way you will be able to extend the Class easily, without even caring to *recreate* the constructor, but just abstracting the filesystem part.
Something like:
```php
protected function init(
    $shp_handle,    // SHP file handle
    $shp_size,      // SHP file size in bytes
    $shx_handle,    // SHX file handle
    $shx_size,      // SHX file size in bytes
    $dbf_handle,    // DBF file handle
    $dbf_size,      // DBF file size in bytes
    $prj = null,    // Optional - Content of PRJ file as string
    $flags = 0      // Optional - Flags
) {}
```
In your extended class constructor you will only need to collect the handles, file sizes and optional prj file content and then simply call `$this->init(/*all the arguments here...*/)`.
What do you think about that?

**Comment by allartk** [comment]
Last comment is a good idea, this will make extending the class possible. Thank you much.

**Comment by gasparesganga** [comment]
Here you go, [v2.3.0](https://github.com/gasparesganga/php-shapefile/releases/tag/v2.3.0) can be extended with a custom constructor thanks to protected method `init()`.

Thank you for your feedback, I appreciate it, really!

**Comment by allartk** [comment]
For anyone finding this, it is now implemented as:

```php
<?php

namespace AppBundle\Utils\DataConverter;

use ShapeFile\ShapeFile;
use League\Flysystem\File;

class ShapeFlyFile extends ShapeFile
{
    public function __construct(File $shp, File $shx, File $dbf, File $prj, $flags = 0)
    {
        $this->init(
            $shp->readStream(),
            $shp->getSize(),
            $shx->readStream(),
            $shx->getSize(),
            $dbf->readStream(),
            $dbf->getSize(),
            ($prj) ? $prj->read() : null,
            $flags
        );
    }
}
```

**Pull request closed without merging**
